### ISSUE TITLE
Convert ORM library or create new branch

### ISSUE THREAD

**Issue by tmtung144** [Ferdysd96/nestjs-permission-boilerplate#4]
This is probably a more personal suggestion, I think it's quite selfish. Personally, I like the way you write decentralized functionality, it suits me very well.

With **TypeORM** I found it quite good, but after finding out **[Prisma](https://www.prisma.io/)** I think it should be applied to this project.
It has a much simpler and cleaner way of coding.

Can you think about implementing it?

Thank you so much for this project!

**Comment by Ferdysd96** [comment]
Hi, thanks for supporting the repository.

I haven't had a chance to use **[Prisma](https://www.prisma.io/)** yet, but thanks for the suggestion, later maybe I will implement it in a new branch.
